services:
  - type: web
    name: meu-web-service
    env: node
    plan: free
    repo: https://github.com/Maria19890605/mariajose
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meu-postgres
          property: connectionString

databases:
  - name: mariajose
    plan: free
    region: oregon